# Generated by Django 3.2.2 on 2021-05-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='acc_name',
            field=models.CharField(default='Abc', max_length=25),
        ),
    ]
