# Generated by Django 3.2.2 on 2021-05-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(max_length=150)),
            ],
        ),
    ]
