# Generated by Django 3.2.2 on 2021-05-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_demomodel_demos_demom_txt_4a0cc7_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='demomodel',
            name='demos_demom_txt_4a0cc7_idx',
        ),
    ]
