# Generated by Django 3.2.2 on 2021-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0006_remove_demomodel_demos_demom_txt_4a0cc7_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demomodel',
            index=models.Index(fields=['txt'], name='demos_demom_txt_4a0cc7_idx'),
        ),
    ]
