# Generated by Django 3.2.2 on 2021-05-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0007_demomodel_demos_demom_txt_4a0cc7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='exp',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
