# Generated by Django 3.2.2 on 2021-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0008_alter_sample_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='exp',
            field=models.CharField(max_length=150),
        ),
    ]
