# Generated by Django 3.2.2 on 2021-05-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0010_sample_demos_sampl_exp_a00fca_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sample',
            name='demos_sampl_exp_a00fca_idx',
        ),
    ]
