# Generated by Django 3.2.2 on 2021-05-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0011_remove_sample_demos_sampl_exp_a00fca_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
