# Generated by Django 3.2.2 on 2021-05-31 10:26

from django.db import migrations

def cust_mig(apps, schema_editor):

    sample = apps.get_model("demos", "Sample")

    sample.objects.filter(id__gt=5000, id__lt=6000).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0012_fileupload'),
    ]

    operations = [
        migrations.RunPython(cust_mig),
    ]
