# Generated by Django 3.2.2 on 2021-05-12 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=50)),
                ('model_num', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=25)),
                ('gears', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('muscle', 'Muscle'), ('suv', 'SUV'), ('supersport', 'SUPER_SPORT'), ('convertible', 'CONVERTIBLE'), ('pickup', 'PICK_UP'), ('hatchback', 'HATCHBACK'), ('4x4offroad', '4X4_OFFROAD')], help_text='Choose from the list', max_length=20)),
                ('is_dct', models.BooleanField()),
            ],
            options={
                'ordering': ('model_name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('origin', models.CharField(max_length=25)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=50)),
                ('model_num', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=25)),
                ('gears', models.PositiveSmallIntegerField()),
                ('inspired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.car')),
            ],
            options={
                'ordering': ('model_name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='display',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vehicles.displayplace'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, to='vehicles.Manufacturer'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=50)),
                ('model_num', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=25)),
                ('gears', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('adventure', 'ADV'), ('caferacer', 'CAFE_RACER'), ('supersport', 'SUPER_SPORT'), ('cruiser', 'CRUISER'), ('commuter', 'COMMUTER'), ('streetnaked', 'STREET_NAKED'), ('tourer', 'TOURER')], help_text='Choose from the list', max_length=15)),
                ('tubeless_tyres', models.BooleanField()),
                ('manufacturer', models.ManyToManyField(blank=True, to='vehicles.Manufacturer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('model_name',),
                'abstract': False,
            },
        ),
    ]
