# Generated by Django 3.2.2 on 2021-05-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='manufacturer',
            field=models.ManyToManyField(to='vehicles.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='display',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.displayplace'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ManyToManyField(to='vehicles.Manufacturer'),
        ),
    ]
