# Generated by Django 3.2.2 on 2021-05-23 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.place')),
                ('houses', models.PositiveSmallIntegerField()),
            ],
            bases=('vehicles.place',),
        ),
    ]
