# Generated by Django 3.2.2 on 2021-05-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='logo',
        ),
    ]
